<?php

// Initializes the autoloader generated by composer.
$loader = require 'bin/vendor/autoload.php';
$loader->register();

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

require 'lib/Framework/Core.php';

$app = new Framework\Core();

$app->map('/', function() {
  return new Response('This is home page');
});

$app->map('/about', function() {
  return new Response('This is about page');
});

$request = Request::createFromGlobals();

$response = $app->handle($request);
$response->send();
